// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2mzsSAP8VmfjXXA6LGPxO8gl60c62oxA',
    appId: '1:189249212411:web:8b3ca51c84fa102415055e',
    messagingSenderId: '189249212411',
    projectId: 'gdg1-e42ab',
    authDomain: 'gdg1-e42ab.firebaseapp.com',
    databaseURL: 'https://gdg1-e42ab-default-rtdb.firebaseio.com',
    storageBucket: 'gdg1-e42ab.appspot.com',
    measurementId: 'G-6TRXLMV5K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZTFNVjuNT70sI9nBl2qHdzocjp5rNmfc',
    appId: '1:189249212411:android:379d405228a2a62d15055e',
    messagingSenderId: '189249212411',
    projectId: 'gdg1-e42ab',
    databaseURL: 'https://gdg1-e42ab-default-rtdb.firebaseio.com',
    storageBucket: 'gdg1-e42ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAhUunAPNYkKvF5BLjflgcIFbh-wD2sk',
    appId: '1:189249212411:ios:e31444f99ceebc2c15055e',
    messagingSenderId: '189249212411',
    projectId: 'gdg1-e42ab',
    databaseURL: 'https://gdg1-e42ab-default-rtdb.firebaseio.com',
    storageBucket: 'gdg1-e42ab.appspot.com',
    androidClientId: '189249212411-io84u4rnjl2pi6sn0g00jimc6n0q963a.apps.googleusercontent.com',
    iosClientId: '189249212411-6qap56d5r86ki28e3afl15envb30eq1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.golddustHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAhUunAPNYkKvF5BLjflgcIFbh-wD2sk',
    appId: '1:189249212411:ios:e31444f99ceebc2c15055e',
    messagingSenderId: '189249212411',
    projectId: 'gdg1-e42ab',
    databaseURL: 'https://gdg1-e42ab-default-rtdb.firebaseio.com',
    storageBucket: 'gdg1-e42ab.appspot.com',
    androidClientId: '189249212411-io84u4rnjl2pi6sn0g00jimc6n0q963a.apps.googleusercontent.com',
    iosClientId: '189249212411-6qap56d5r86ki28e3afl15envb30eq1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.golddustHomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDggsbHP3W3XSG8_w2MRacvOkxRfvw74z8',
    appId: '1:189249212411:web:fc1fb4693a4d3e9915055e',
    messagingSenderId: '189249212411',
    projectId: 'gdg1-e42ab',
    authDomain: 'gdg1-e42ab.firebaseapp.com',
    databaseURL: 'https://gdg1-e42ab-default-rtdb.firebaseio.com',
    storageBucket: 'gdg1-e42ab.appspot.com',
    measurementId: 'G-NNHPS6VC2P',
  );
}
